package game;

public class Map {

  static String[] level = new String[] {
      "     BBBBBBBBBBBBBBBBBBBBBBBB     ",
      "     BRRRR      RRRRRRRRRRRRB     ",
      "BBBBBBRRRRRRRRRRRRRRRRRRRRRRBBBBBB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "B  RRRRRRRRRRRRRRRRRRRRRRRRRR   RB",
      "B   RRRRRRRRRRRRRRRRRRRRRRRRR   RB",
      "B    RRRRRRRRRRRRRRRRRRRRRRRR   RB",
      "BRR  RRRRRRRRRRRRRRRRRRRRRRRR   RB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRB",
      "BRRRRRRRRRRR   RR    RRRRRRRRRRRRB",
      "BRRRRRRRRRRR   RR    RR         RB",
      "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",};

}
